#!/bin/bash

# rlwrap with cargo breaks output of the test scripts.
#rlwrap cargo run --quiet -- "$@"

# Option 1 is hardcoding target/debug/fml
# Downsides:
# - it's not guaranteed to be the same everywhere
# - it's easier to forget to recompile
# - it makes it harder to switch between debug and release
# - Not available on linux and macOS CI, installing it complicates the config
#rlwrap target/debug/fml "$@"

# Option 2 is removing rlwrap.
# People can still use rlwrap around ./fml if they want to.
# Downsides:
# - cargo really slows everything down when calling ./fml many times
#   (like when running and especially generating tests)
#cargo run --quiet -- "$@"

# Option 3 - simply call the binary
target/debug/fml "$@"

# TODO Make release default but optional.
